name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake make gcc g++ python3
      
    - name: Create build directory
      run: mkdir -p build && cd build
      
    - name: Configure with CMake
      run: cd build && cmake ..
      
    - name: Build project
      run: cd build && make
      
    - name: Run tests
      run: |
        cd build
        ./test > test_output.log 2>&1
      continue-on-error: true
      
    - name: Analyze test results
      run: |
        cat build/test_output.log
        python3 .github/workflows/analyze_test_results.py build/test_output.log
