name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake make gcc

    - name: Compile && Make Kernel
      run: |
        cd build
        cmake ..
        make kernel

    - name: Compile && Make test
      run: |
        cd build
        cmake ..
        make test

    - name: Run Tests
      run: |
        cd ..
        ./test
