name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake make gcc

    - name: Make commands.sh executable
      run: chmod +x devtool/commands.sh

    - name: Build kernel
      run: devtool/commands.sh mkk

    - name: Build tests
      run: devtool/commands.sh mkt
      
    - name: Run tests
      run: |
        ./test
